In [115]:
import netCDF4 as nc  
import numpy as np
import pandas as pd


In [7]:
gfs_fcst=nc.Dataset(r"C:\Users\LiangXuewei\Desktop\HadISST_sst.nc")  

In [3]:
print(gfs_fcst)  

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_CLASSIC data model, file format NETCDF3):
    Title: Monthly version of HadISST sea surface temperature component
    description: HadISST 1.1 monthly average sea surface temperature
    institution: Met Office Hadley Centre
    source: HadISST
    reference: Rayner, N. A., Parker, D. E., Horton, E. B., Folland, C. K., Alexander, L. V., Rowell, D. P., Kent, E. C., Kaplan, A.  Global analyses of sea surface temperature, sea ice, and night marine air temperature since the late nineteenth century J. Geophys. Res.Vol. 108, No. D14, 4407 10.1029/2002JD002670
    Conventions: CF-1.0
    history: 23/3/2018 converted to netcdf from pp format
    supplementary_information: Updates and supplementary information will be available from http://www.metoffice.gov.uk/hadobs/hadisst
    comment: Data restrictions: for academic research use only. Data are Crown copyright see (http://www.opsi.gov.uk/advice/crown-copyright/copyright-guidance/index.htm

In [4]:
print(gfs_fcst.variables.keys()) 

odict_keys(['time', 'time_bnds', 'latitude', 'longitude', 'sst'])


In [13]:
print(gfs_fcst.variables['longitude'].ncattrs())

['units', 'long_name', 'standard_name']


In [117]:
time = gfs_fcst.variables['time']
# print (time)
from netCDF4 import num2date
valid_dates = num2date(time[:], time.units).tolist()

dates = [d.strftime('%Y-%m-%d-%H-%M') for d in valid_dates]
print(dates)

['1870-01-16-11-59', '1870-02-14-23-59', '1870-03-16-11-59', '1870-04-15-23-59', '1870-05-16-12-00', '1870-06-16-00-00', '1870-07-16-12-00', '1870-08-16-12-00', '1870-09-16-00-00', '1870-10-16-12-00', '1870-11-16-00-00', '1870-12-16-12-00', '1871-01-16-12-00', '1871-02-15-00-00', '1871-03-16-12-00', '1871-04-16-00-00', '1871-05-16-12-00', '1871-06-16-00-00', '1871-07-16-12-00', '1871-08-16-12-00', '1871-09-16-00-00', '1871-10-16-12-00', '1871-11-16-00-00', '1871-12-16-12-00', '1872-01-16-12-00', '1872-02-15-00-00', '1872-03-16-12-00', '1872-04-16-00-00', '1872-05-16-12-00', '1872-06-16-00-00', '1872-07-16-12-00', '1872-08-16-12-00', '1872-09-16-00-00', '1872-10-16-12-00', '1872-11-16-00-00', '1872-12-16-12-00', '1873-01-16-12-00', '1873-02-15-00-00', '1873-03-16-12-00', '1873-04-16-00-00', '1873-05-16-12-00', '1873-06-16-00-00', '1873-07-16-12-00', '1873-08-16-12-00', '1873-09-16-00-00', '1873-10-16-12-00', '1873-11-16-00-00', '1873-12-16-12-00', '1874-01-16-12-00', '1874-02-15-00-00',

In [102]:
lon = gfs_fcst.variables['longitude'][:]
lat = gfs_fcst.variables['latitude'][:]
sst = gfs_fcst.variables['sst'][:]

In [109]:
need_sst = sst[1164:1764, 64:87, 289:301]

In [121]:
print(need_sst.shape) # sst, lat, lon
need_sst = need_sst.reshape((600, -1))

(600, 276)


In [114]:
need_sst.data

array([[-1.0000000e+30, -1.0000000e+30, -1.0000000e+30, ...,
         2.8095434e+01,  2.8064461e+01,  2.8051693e+01],
       [-1.0000000e+30, -1.0000000e+30, -1.0000000e+30, ...,
         2.7645767e+01,  2.7614792e+01,  2.7654503e+01],
       [-1.0000000e+30, -1.0000000e+30, -1.0000000e+30, ...,
         2.7992331e+01,  2.7934006e+01,  2.7931244e+01],
       ...,
       [-1.0000000e+30, -1.0000000e+30, -1.0000000e+30, ...,
         2.9098961e+01,  2.9216089e+01,  2.9314819e+01],
       [-1.0000000e+30, -1.0000000e+30, -1.0000000e+30, ...,
         2.9332481e+01,  2.9491314e+01,  2.9573778e+01],
       [-1.0000000e+30, -1.0000000e+30, -1.0000000e+30, ...,
         2.9070673e+01,  2.9217140e+01,  2.9293533e+01]], dtype=float32)

In [120]:
df = pd.DataFrame(need_sst.data, index=dates[1164:1764])
df.to_csv(r'c:/Users/LiangXuewei/Desktop/sst.csv')

In [126]:
a = np.array([[1,2,3], [4,5,6]]).reshape(3,-1)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [130]:
lat[64:87]

array([25.5, 24.5, 23.5, 22.5, 21.5, 20.5, 19.5, 18.5, 17.5, 16.5, 15.5,
       14.5, 13.5, 12.5, 11.5, 10.5,  9.5,  8.5,  7.5,  6.5,  5.5,  4.5,
        3.5], dtype=float32)

In [129]:
lon[289:301]

array([109.5, 110.5, 111.5, 112.5, 113.5, 114.5, 115.5, 116.5, 117.5,
       118.5, 119.5, 120.5], dtype=float32)

In [52]:
valid_dates[1164:1764]

[datetime.datetime(1967, 1, 16, 12, 0),
 datetime.datetime(1967, 2, 15, 0, 0),
 datetime.datetime(1967, 3, 16, 12, 0),
 datetime.datetime(1967, 4, 16, 0, 0),
 datetime.datetime(1967, 5, 16, 12, 0),
 datetime.datetime(1967, 6, 16, 0, 0),
 datetime.datetime(1967, 7, 16, 12, 0),
 datetime.datetime(1967, 8, 16, 12, 0),
 datetime.datetime(1967, 9, 16, 0, 0),
 datetime.datetime(1967, 10, 16, 12, 0),
 datetime.datetime(1967, 11, 16, 0, 0),
 datetime.datetime(1967, 12, 16, 12, 0),
 datetime.datetime(1968, 1, 16, 12, 0),
 datetime.datetime(1968, 2, 15, 0, 0),
 datetime.datetime(1968, 3, 16, 12, 0),
 datetime.datetime(1968, 4, 16, 0, 0),
 datetime.datetime(1968, 5, 16, 12, 0),
 datetime.datetime(1968, 6, 16, 0, 0),
 datetime.datetime(1968, 7, 16, 12, 0),
 datetime.datetime(1968, 8, 16, 12, 0),
 datetime.datetime(1968, 9, 16, 0, 0),
 datetime.datetime(1968, 10, 16, 12, 0),
 datetime.datetime(1968, 11, 16, 0, 0),
 datetime.datetime(1968, 12, 16, 12, 0),
 datetime.datetime(1969, 1, 16, 12, 0),
 dat